### ISSUE TITLE
PugJS

### ISSUE THREAD

**Issue by karneaud** [interfaced/zombiebox-extension-cutejs#1]
How hard would it be to use https://pugjs.org/api/reference.html ??

**Comment by l1bbcsg** [comment]
Should not be hard. CuteJS and Pug are both in their essence template engines that transform their syntax into something that renders. In ZombieBox case the output should be a class implementing a simple interface.

This extension is a wrapper around CuteJS engine that bridges framework and the template generator.

Adding Pug or any other template engine support could be done by implementing another ZombieBox extension.
All it takes is a class inheriting from `AbstractExtension` that receives a list of files via `watchSources` hook, passes them to Pug and then returns compiled files by emitting `IZBExtension.EVENT_GENERATED`.

Making Closure Compiler happy with the output might be a bit tricky, but shouldn't be too challenging.

**Comment by Allan-Nava** [comment]
How can I add and async xhr only for specifc scene?
